

function(qt_submodule_installation)
    qt_download_submodule(OUT_SOURCE_PATH TARGET_SOURCE_PATH ${ARGV})
    if(QT_UPDATE_VERSION)
        SET(VCPKG_POLICY_EMPTY_PACKAGE enabled PARENT_SCOPE)
    else()
        list(FIND ARGV "PATCHES" patches_pos)
        if(patches_pos GREATER_EQUAL 0)
            LIST(SUBLIST ARGV 0 ${patches_pos} ARGV)
        endif()
        qt_build_submodule(${TARGET_SOURCE_PATH} ${ARGV})
        qt_install_copyright(${TARGET_SOURCE_PATH})
    endif()
endfunction()