cmake_policy(SET CMP0057 NEW)
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET v143)
list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS "-DCMAKE_CXX_STANDARD=17")

set(NO_ASAN openssl)
if(PORT IN_LIST NO_ASAN)
  set(VCPKG_C_FLAGS "-vmg")
  set(VCPKG_CXX_FLAGS "-vmg")
else()
  set(VCPKG_C_FLAGS "-vmg -fsanitize=address")
  set(VCPKG_CXX_FLAGS "-vmg -fsanitize=address")
  set(VCPKG_C_FLAGS_DEBUG "-Oy-")
  set(VCPKG_CXX_FLAGS_DEBUG "-Oy-")
endif()

