cmake_policy(SET CMP0057 NEW)
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
if(PORT STREQUAL gmp)
set(VCPKG_LIBRARY_LINKAGE dynamic)
else()
set(VCPKG_LIBRARY_LINKAGE static)
endif()
set(VCPKG_PLATFORM_TOOLSET v143)
list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS "-DCMAKE_CXX_STANDARD=17")
set(VCPKG_BUILD_TYPE release)

set(IS_LTO TRUE)
set(NO_LTO abseil double-conversion gmp grpc libffi protobuf re2 upb)
if(PORT IN_LIST NO_LTO)
    set(IS_LTO FALSE)
endif()

set(VCPKG_C_FLAGS "-vmg")
set(VCPKG_CXX_FLAGS "-vmg")

if(IS_LTO)
    set(VCPKG_CXX_FLAGS_RELEASE "-GL -Gw -GS- -arch:AVX512 -favor:AMD64")
    set(VCPKG_C_FLAGS_RELEASE "-GL -Gw -GS- -arch:AVX512 -favor:AMD64")
    set(VCPKG_LINKER_FLAGS_RELEASE "-OPT:ICF=3 -LTCG")
endif()
