#asan
cmake_policy(SET CMP0057 NEW)
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_FIXUP_ELF_RPATH ON)
list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS "-DCMAKE_CXX_STANDARD=17")
set(VCPKG_BUILD_TYPE release)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)

if(EXISTS /etc/debian_version)
  set(IS_DEBIAN TRUE)
elseif(EXISTS /etc/os-release)
  file(READ /etc/os-release _s)
  if(_s MATCHES "openSUSE")
    if(PORT STREQUAL protobuf OR PORT STREQUAL grpc)
      set(VCPKG_LIBRARY_LINKAGE static)
    endif()
  endif()
endif()

set(VCPKG_CXX_FLAGS "-fsanitize=address,undefined,pointer-compare,pointer-subtract -fsanitize-address-use-after-scope -fstack-protector-all -fstack-clash-protection -fno-omit-frame-pointer -U_FORTIFY_SOURCE")
set(VCPKG_C_FLAGS   "-fsanitize=address,undefined,pointer-compare,pointer-subtract -fsanitize-address-use-after-scope -fstack-protector-all -fstack-clash-protection -fno-omit-frame-pointer -U_FORTIFY_SOURCE")

if(PORT STREQUAL glib)
  if(IS_DEBIAN)
    set(VCPKG_LINKER_FLAGS "-Wl,--no-as-needed -ldl")
  endif()
endif()
