# asan
cmake_policy(SET CMP0057 NEW)
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_SANITIZE address)
list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS "-DCMAKE_CXX_STANDARD=17")

set(_x64_asan_runtime_root "")
if(DEFINED ENV{VCToolsInstallDir})
  file(TO_CMAKE_PATH "$ENV{VCToolsInstallDir}" _x64_asan_runtime_root)
  string(REGEX REPLACE "/+$" "" _x64_asan_runtime_root "${_x64_asan_runtime_root}")
  if(NOT EXISTS "${_x64_asan_runtime_root}/lib/x64/clang_rt.asan_dynamic_runtime_thunk-x86_64.lib")
    set(_x64_asan_runtime_root "")
  endif()
endif()

if(NOT _x64_asan_runtime_root AND DEFINED ENV{VCINSTALLDIR})
  file(TO_CMAKE_PATH "$ENV{VCINSTALLDIR}" _vcinstall_dir)
  string(REGEX REPLACE "/+$" "" _vcinstall_dir "${_vcinstall_dir}")
  file(GLOB _x64_asan_runtime_roots LIST_DIRECTORIES true "${_vcinstall_dir}/Tools/MSVC/*")
  foreach(_candidate IN LISTS _x64_asan_runtime_roots)
    if(EXISTS "${_candidate}/lib/x64/clang_rt.asan_dynamic_runtime_thunk-x86_64.lib")
      set(_x64_asan_runtime_root "${_candidate}")
    endif()
  endforeach()
  unset(_candidate)
  unset(_vcinstall_dir)
endif()

if(NOT _x64_asan_runtime_root)
  message(FATAL_ERROR
    "Unable to find the MSVC x64 AddressSanitizer runtime. "
    "Install an MSVC toolset that provides clang_rt.asan_dynamic_runtime_thunk-x86_64.lib.")
endif()

set(_x64_asan_runtime_lib_dir "${_x64_asan_runtime_root}/lib/x64")
string(APPEND VCPKG_LINKER_FLAGS " /LIBPATH:\"${_x64_asan_runtime_lib_dir}\"")

set(_x64_asan_include_dir "${_x64_asan_runtime_root}/include")
if(NOT EXISTS "${_x64_asan_include_dir}/sanitizer/asan_interface.h")
  set(_x64_asan_include_dir "${_x64_asan_runtime_root}/crt/src")
endif()
if(NOT EXISTS "${_x64_asan_include_dir}/sanitizer/asan_interface.h")
  message(FATAL_ERROR
    "Unable to find the MSVC x64 AddressSanitizer headers under ${_x64_asan_runtime_root}.")
endif()
set(_x64_asan_include_flag " /I\"${_x64_asan_include_dir}\"")

set(_x64_asan_runtime_bin_dir "${_x64_asan_runtime_root}/bin/Hostx64/x64")
if(EXISTS "${_x64_asan_runtime_bin_dir}/clang_rt.asan_dynamic-x86_64.dll")
  set(ENV{PATH} "${_x64_asan_runtime_bin_dir};$ENV{PATH}")
endif()

unset(_x64_asan_runtime_bin_dir)
unset(_x64_asan_include_dir)
unset(_x64_asan_runtime_lib_dir)
unset(_x64_asan_runtime_roots)
unset(_x64_asan_runtime_root)

set(IS_ASAN TRUE)
set(NO_ASAN icu openssl python3)
if(PORT IN_LIST NO_ASAN)
  set(IS_ASAN FALSE)
endif()
if(PORT MATCHES "^qt")
  set(IS_ASAN FALSE)
endif()

if(IS_ASAN)
  set(VCPKG_C_FLAGS "-vmg -fsanitize=address -D_DISABLE_VECTOR_ANNOTATION -D_DISABLE_STRING_ANNOTATION${_x64_asan_include_flag}")
  set(VCPKG_CXX_FLAGS "-vmg -fsanitize=address -D_DISABLE_VECTOR_ANNOTATION -D_DISABLE_STRING_ANNOTATION${_x64_asan_include_flag}")
  set(VCPKG_C_FLAGS_DEBUG "-Oy-")
  set(VCPKG_CXX_FLAGS_DEBUG "-Oy-")
else()
  set(VCPKG_C_FLAGS "-vmg")
  set(VCPKG_CXX_FLAGS "-vmg")
endif()
unset(_x64_asan_include_flag)
