# asan
cmake_policy(SET CMP0057 NEW)
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET v145)
set(VCPKG_SANITIZE address)
list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS "-DCMAKE_CXX_STANDARD=17")

set(IS_ASAN TRUE)
set(NO_ASAN icu openssl python3)
if(PORT IN_LIST NO_ASAN)
  set(IS_ASAN FALSE)
endif()
if(PORT MATCHES "^qt")
  set(IS_ASAN FALSE)
endif()

if(IS_ASAN)
  set(VCPKG_C_FLAGS "-vmg -fsanitize=address")
  set(VCPKG_CXX_FLAGS "-vmg -fsanitize=address")
  set(VCPKG_C_FLAGS_DEBUG "-Oy-")
  set(VCPKG_CXX_FLAGS_DEBUG "-Oy-")
else()
  set(VCPKG_C_FLAGS "-vmg")
  set(VCPKG_CXX_FLAGS "-vmg")
endif()
